name: Release

on:
  # This action should be run in workflows triggered by `pull_request_target`
  # (not by regular `pull_request`!)
  pull_request_target:
    branches:
      # Create a release whenever a PR is merged into one of these branches:
      - main
    types:
      - closed
  # Allow manually triggering a release via the "Run workflow" button:
  workflow_dispatch:

permissions:
  # Needed to push the release commit and tag:
  contents: write
  # Needed to comment on PRs and issues:
  issues: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-24.04
    # Only run for manual runs or merged PRs with the "release" label:
    if: >
      github.event_name == 'workflow_dispatch'
      || (github.event.pull_request.merged == true && contains(github.event.pull_request.labels.*.name, 'release'))
    steps:
      - name: Checkout source
        uses: actions/checkout@v6
        with:
          # Check out all history so that the previous release tag can be
          # found:
          fetch-depth: 0

      - name: Prepare release
        uses: datalad/release-action/release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          #pypi-token: ${{ secrets.PYPI_TOKEN }}
